spring.application.name=emp_mngt

spring.datasource.url=jdbc:postgresql://localhost:5432/emp_mngt
spring.datasource.username=postgres
spring.datasource.password=suraj123
spring.datasource.driver-class-name=org.postgresql.Driver

#it show the version of website
server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Security config
#spring.security.user.name=suraj
#spring.security.user.password=1234
jwt.secretKey=9d8fasf098d8asfdsfdsf8098mwjer897v4yn8gvdjkzghrt678uyty8765u6578oew5iklkjf5

